# CMake import target configuration file

set(BUGTRAP_BASE_DIR "${CU_ROOT_DIR}/3rdparty/bugtrap")

set(BUGTRAP_ARCH_POSTFIX "")
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(BUGTRAP_ARCH_POSTFIX "-x64")
endif()

add_library(BugTrap SHARED IMPORTED)

set_target_properties(BugTrap PROPERTIES
	IMPORTED_IMPLIB ${BUGTRAP_BASE_DIR}/BugTrap${BUGTRAP_ARCH_POSTFIX}.lib
	IMPORTED_LOCATION ${BUGTRAP_BASE_DIR}/BugTrap${BUGTRAP_ARCH_POSTFIX}.dll
	INTERFACE_INCLUDE_DIRECTORIES ${BUGTRAP_BASE_DIR}
	INTERFACE_COMPILE_DEFINITIONS "HAVE_BUGTRAP"
)
