function(target_configure_executable TARGET_NAME)
	if(APPLE)
		get_target_property(_is_bundle ${TARGET_NAME} MACOSX_BUNDLE)
		if(_is_bundle)
			set_target_properties(${TARGET_NAME} PROPERTIES INSTALL_RPATH "@executable_path/../Frameworks")
		else()
			set_target_properties(${TARGET_NAME} PROPERTIES INSTALL_RPATH "@executable_path/../lib")
		endif()
	elseif(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX)
		set_target_properties(${TARGET_NAME} PROPERTIES INSTALL_RPATH "../lib")
	endif()
endfunction()
